### PR TITLE
added animation and rearranged the homepage elements

### PR DESCRIPTION
**Pull request by raghav1482**
@sandys sir , I have made changes to home page (issue #11) kindly merge to main branch

### CODE REVIEW

**Comment by raghav1482** [comment]
@sandys  sir i have made the changes (issue #11)under GSSOC 2023 ,  kindly review my PR#19

**Comment by sandys** [comment]
@raghav1482 please create a loom video showing how the site looks with these changes and paste the link here. we will review.

**Comment by raghav1482** [comment]
@sandys  sir here is the link for the video https://drive.google.com/file/d/1xGjxM_ZEKi82Df9r56Hs7aTdz7rEK0CQ/view?usp=sharing kindly review (PR #19)

**Comment by sandys** [comment]
@raghav1482 interesting work!
but some issues. however, i would like to work+mentor with you personally on this topic.

can you please sign up to the arakoo discord and message me there ?

https://discord.gg/KQkqyNhb

**Pull request closed without merging**
